spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/venus
    username: postgres
    password: password
  jpa:
    show-sql: true
frontend:
  base-url: http://localhost:3000
backend:
  base-url: http://localhost:8080