spring:
    datasource:
        name: jdbc/DataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/venus
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: validate
#            ddl-auto: create-drop
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect