spring:
  datasource:
    name: jdbc/DataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/venus
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect