spring:
    datasource:
        name: jdbc/DataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/venus
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

frontend:
  base-url: http://localhost:3000